# Bag 1 : Import Library

In [12]:
import pandas as pd                    # Baca data, olah data, grouping, merging
import numpy as np                     # Kalkulasi, array, matrik
import matplotlib.pyplot as plt        # Grafik sederhana
import seaborn as sns                  # Grafik tinggi = peta, heatmap

# Bag 2 : Baca Data

In [13]:
df = pd.read_csv('ds_salaries.csv')
df.head(5) # tampilkan 5 data teratas

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M

In [14]:
df.tail() # terakhir

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
3750,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
3751,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
3752,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
3753,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
3754,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

In [15]:
df.sample() # mengambil secara acak 1 data

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
2846,2022,MI,FT,Data Manager,98000,USD,98000,US,0,US,M

# Bag 3 : Eksplorasi Data

In [16]:
df.shape

(3755, 11)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           3755 non-null   int64
 1   experience_level    3755 non-null   object
 2   employment_type     3755 non-null   object
 3   job_title           3755 non-null   object
 4   salary              3755 non-null   int64
 5   salary_currency     3755 non-null   object
 6   salary_in_usd       3755 non-null   int64
 7   employee_residence  3755 non-null   object
 8   remote_ratio        3755 non-null   int64
 9   company_location    3755 non-null   object
 10  company_size        3755 non-null   object
dtypes: int64(4), object(7)
memory usage: 322.8+ KB

In [18]:
df['employment_type'].unique()

array(['FT', 'CT', 'FL', 'PT'], dtype=object)

# Bag 4 : Cleaning Data

# Missing Value

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           3755 non-null   int64
 1   experience_level    3755 non-null   object
 2   employment_type     3755 non-null   object
 3   job_title           3755 non-null   object
 4   salary              3755 non-null   int64
 5   salary_currency     3755 non-null   object
 6   salary_in_usd       3755 non-null   int64
 7   employee_residence  3755 non-null   object
 8   remote_ratio        3755 non-null   int64
 9   company_location    3755 non-null   object
 10  company_size        3755 non-null   object
dtypes: int64(4), object(7)
memory usage: 322.8+ KB

In [20]:
df.isnull().sum() # menghitung jumlah data yang kosong per kolomnya

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

# Data Duplikat

In [21]:
df.duplicated().sum()

np.int64(1171)

In [22]:
df.duplicated().sum()

np.int64(1171)

solusi : dihapus

In [23]:
df.drop_duplicates(inplace=True) # di dataset itu

In [24]:
df2 = df.drop_duplicates() # simpan dataset yg sudah bersih dari duplikat df2

In [25]:
df2

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M
...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
3751,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
3752,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
3753,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
3754,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

# Bag 5 : Stat Des

In [26]:
df2.describe() # stat des kolom numerik

         work_year        salary  salary_in_usd  remote_ratio
count  2584.000000  2.584000e+03    2584.000000   2584.000000
mean   2022.301084  2.103653e+05  133409.280186     50.483746
std       0.749179  8.080375e+05   67136.837329     48.163707
min    2020.000000  6.000000e+03    5132.000000      0.000000
25%    2022.000000  9.000000e+04   84975.000000      0.000000
50%    2022.000000  1.346300e+05  130000.000000     50.000000
75%    2023.000000  1.825625e+05  175000.000000    100.000000
max    2023.000000  3.040000e+07  450000.000000    100.000000

In [27]:
df2.describe(include= 'object') # kolom yg bertipe string/kategori

,experience_level,employment_type,job_title,salary_currency,employee_residence,company_location,company_size
count,2584,2584,2584,2584,2584,2584,2584
unique,4,4,93,20,78,72,3
top,SE,FT,Data Engineer,USD,US,US,M
freq,1554,2547,598,2107,1893,1929,2028

# Bag 6 : Mapping Kategori

In [28]:
df2['experience_level'].unique()

array(['SE', 'MI', 'EN', 'EX'], dtype=object)



*   SE = SENIOR
*   MI = MIDDLE
*   EN = ENTRY
*   EX = EXECUTIVE

dictionary = type data di python

In [29]:
dict_exp_level = {
    'SE' : 'SENIOR',
    'MI' : 'MIDDLE',
    'EN' : 'ENTRY',
    'EX' : 'EXECUTIVE'
}

In [30]:
df2['experience_level'] = (df2['experience_level'].map(dict_exp_level))

In [31]:
df2['experience_level'].unique()

array(['SENIOR', 'MIDDLE', 'ENTRY', 'EXECUTIVE'], dtype=object)

In [32]:
dict_exp_level = {
    'FT' : 'Full Time',
    'CT' : 'Contract',
    'FL' : 'Freelance',
    'PT' : 'Part Time'
}

In [33]:
df2['employment_type'] = (df2['employment_type'].map(dict_exp_level))

In [34]:
df2['employment_type'].unique()

array(['Full Time', 'Contract', 'Freelance', 'Part Time'], dtype=object)

In [35]:
df2['remote_ratio'].unique()

array([100,   0,  50])

ratio 0 = Onsite
ratio 50 = Hybrid
ratio 100 = WFH

In [36]:
dict_remote_ratio = {
    '0' : 'ONSITE',
    '50' : 'HYBRID',
    '100' : 'REMOTE'
}

bikin kolom kategori_remote

In [37]:
df2['remote_category'] = (df2['remote_ratio'].map(dict_remote_ratio))

In [38]:
df2

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,remote_category
0,2023,SENIOR,Full Time,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L,NaN
1,2023,MIDDLE,Contract,ML Engineer,30000,USD,30000,US,100,US,S,NaN
2,2023,MIDDLE,Contract,ML Engineer,25500,USD,25500,US,100,US,S,NaN
3,2023,SENIOR,Full Time,Data Scientist,175000,USD,175000,CA,100,CA,M,NaN
4,2023,SENIOR,Full Time,Data Scientist,120000,USD,120000,CA,100,CA,M,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,SENIOR,Full Time,Data Scientist,412000,USD,412000,US,100,US,L,NaN
3751,2021,MIDDLE,Full Time,Principal Data Scientist,151000,USD,151000,US,100,US,L,NaN
3752,2020,ENTRY,Full Time,Data Scientist,105000,USD,105000,US,100,US,S,NaN
3753,2020,ENTRY,Contract,Business Data Analyst,100000,USD,100000,US,100,US,L,NaN
3754,2021,SENIOR,Full Time,Data Science Manager,7000000,INR,94665,IN,50,IN,L,NaN

# EDA

In [39]:
df2['experience_level'].value_counts()

experience_level
SENIOR       1554
MIDDLE        664
ENTRY         270
EXECUTIVE      96
Name: count, dtype: int64

ada berapa employment fulltime

In [40]:
df2['employment_type'].value_counts(normalize = True)

employment_type
Full Time    0.985681
Part Time    0.006579
Contract     0.003870
Freelance    0.003870
Name: proportion, dtype: float64

In [41]:
df2['employment_type'].value_counts()

employment_type
Full Time    2547
Part Time      17
Contract       10
Freelance      10
Name: count, dtype: int64

# Bag 8 : Grouping Data

pivot table ( ga ada jadi kolom )

berapakah rata-rata gaji berdasarkan exprience_level?

In [42]:
df2.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size', 'remote_category'],
      dtype='object')

In [43]:
df2.groupby('experience_level')['salary'].mean()

experience_level
ENTRY        199203.914815
EXECUTIVE    252675.343750
MIDDLE       276429.332831
SENIOR       181462.650579
Name: salary, dtype: float64

tampilkan data maksimum dari salary berdasarkan employment_type

In [44]:
df2.groupby('employment_type')['salary'].max()

employment_type
Contract       416000
Freelance     2400000
Full Time    30400000
Part Time      400000
Name: salary, dtype: int64

In [45]:
df2.groupby(['experience_level', 'employment_type'])[['salary', 'salary_in_usd']].mean()

                                         salary  salary_in_usd
experience_level employment_type
ENTRY            Contract          64500.000000   65234.500000
                 Freelance         75000.000000   75000.000000
                 Full Time        208954.654762   74564.626984
                 Part Time         60677.428571   38885.000000
EXECUTIVE        Contract         416000.000000  416000.000000
                 Full Time        250956.136842  188710.610526
MIDDLE           Contract          78600.000000   78600.000000
                 Freelance        515511.000000   41615.600000
                 Full Time        276604.488479  102742.781874
                 Part Time        169666.666667   42561.000000
SENIOR           Contract          97500.000000   97500.000000
                 Freelance         53333.333333   53333.333333
                 Full Time        181819.211750  154165.019367

In [46]:
df2.groupby(['company_size', 'remote_ratio'])[['salary', 'salary_in_usd']].max().reset_index()

  company_size  remote_ratio    salary  salary_in_usd
0            L             0   4900000         423834
1            L            50  11000000         423000
2            L           100  30400000         412000
3            M             0   2500000         450000
4            M            50   1800000         173000
5            M           100   6600000         376080
6            S             0    720000         275000
7            S            50   8500000         165000
8            S           100   4450000         416000

In [47]:
df2.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size', 'remote_category'],
      dtype='object')

In [48]:
df2.groupby('experience_level').agg({
    'salary' : ['max', 'min', 'mean'],
    'work_year' : 'mean'
})

                    salary                          work_year
                       max    min           mean         mean
experience_level
ENTRY              6600000   6000  199203.914815  2021.940741
EXECUTIVE          6000000  15000  252675.343750  2022.291667
MIDDLE            30400000   7500  276429.332831  2022.150602
SENIOR             7500000   8000  181462.650579  2022.428571

In [49]:
df2.groupby('job_title').agg({
    'salary' : ['sum', 'min', 'mean'],
    'experience_level' : 'size'
}).reset_index()

                        job_title    salary                         \
                                        sum     min           mean
0   3D Computer Vision Researcher    480000   10000  120000.000000
1                    AI Developer   1509000    6000  137181.818182
2                   AI Programmer    110000   40000   55000.000000
3                    AI Scientist   4405000   12000  275312.500000
4              Analytics Engineer  13559160    7500  149001.758242
..                            ...       ...     ...            ...
88              Research Engineer   5461854   60000  165510.727273
89             Research Scientist   9940099   23000  152924.600000
90         Software Data Engineer    150000   50000   75000.000000
91             Staff Data Analyst     15000   15000   15000.000000
92           Staff Data Scientist    105000  105000  105000.000000

   experience_level
               size
0                 4
1                11
2                 2
3                16
4                91
..              ...
88               33
89               65
90                2
91                1
92                1

[93 rows x 5 columns]

# Bag 9 : Sorting

In [50]:
df3 = df2.sort_values(by = ['work_year', 'experience_level'], ascending = True) # urutin data berdasarkan gaji terendah

In [51]:
df2

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,remote_category
0,2023,SENIOR,Full Time,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L,NaN
1,2023,MIDDLE,Contract,ML Engineer,30000,USD,30000,US,100,US,S,NaN
2,2023,MIDDLE,Contract,ML Engineer,25500,USD,25500,US,100,US,S,NaN
3,2023,SENIOR,Full Time,Data Scientist,175000,USD,175000,CA,100,CA,M,NaN
4,2023,SENIOR,Full Time,Data Scientist,120000,USD,120000,CA,100,CA,M,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,SENIOR,Full Time,Data Scientist,412000,USD,412000,US,100,US,L,NaN
3751,2021,MIDDLE,Full Time,Principal Data Scientist,151000,USD,151000,US,100,US,L,NaN
3752,2020,ENTRY,Full Time,Data Scientist,105000,USD,105000,US,100,US,S,NaN
3753,2020,ENTRY,Contract,Business Data Analyst,100000,USD,100000,US,100,US,L,NaN
3754,2021,SENIOR,Full Time,Data Science Manager,7000000,INR,94665,IN,50,IN,L,NaN